# SnapLink - Coolify Deployment Configuration
# This file is for reference. Actual configuration happens in Coolify UI.

version: '3'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: snaplink
      POSTGRES_USER: snaplink
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U snaplink']
      interval: 10s
      timeout: 5s
      retries: 5

  # SnapLink Application
  snaplink:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://snaplink:${DB_PASSWORD}@postgres:5432/snaplink
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:

# Coolify Configuration Notes:
# 1. Deploy from GitHub: ibuzzardo/snaplink
# 2. Select branch: main (auto-deploy on push)
# 3. Build command: npm run build
# 4. Start command: npm start
# 5. Set all environment variables listed above
# 6. Enable health check: /api/health (should return 200)
# 7. Set container name: snaplink-app
# 8. Expose port: 3000
# 9. Configure domain: snaplink.72.60.194.93.nip.io (or custom domain)
# 10. Enable SSL/TLS via Let's Encrypt (automatic in Coolify)
